Fix optee-client build by adding the missing LDFLAGS statement in the makefile
Honour the LDFLAGS also in the libteec and tee-supplicant.

Fixes:

ERROR: optee-client-1.1.0+renesas+gitAUTOINC+db9c64d458-r0 do_package_qa:
QA Issue: No GNU_HASH in the elf binary: /usr/bin/tee-supplicant' [ldflags]

Bug-AGL: SPEC-509

Change-Id: I6cb4f2f6c54945ef24a7ff72441c6d91b999b9a4
Signed-off-by: Jan-Simon Möller <jsmoeller@linuxfoundation.org>