[COMMUNITY] gstreamer1.0-plugins-base: disable ivorbis
Backport YP 2.3 Poky Meta change to disable ivorbis.
It is not expected to be required by default and removes
a dependency on tremor which is no longer in oe-core.

Fixes:
ERROR: Nothing PROVIDES 'tremor' (but meta-renesas/meta-rcar-gen3/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.6.3.bb DEPENDS on or otherwise requires it)

Change-Id: If94cbdf38106e36ec4c7c60b9251994607e1775e
Signed-off-by: Ronan Le Martret <ronan.lemartret@iot.bzh>